import openai
from googletrans import Translator
from src.settings.config import OPENAI_TOKEN

translator = Translator()
openai.api_key = OPENAI_TOKEN

async def generate_response(prompt, user_id):
  completions = openai.Completion.create(
    engine="text-davinci-003", # text-davinci-003	 text-curie-001
    prompt=prompt,
    temperature=1,
    max_tokens=2000,
    top_p=1.0,
    frequency_penalty=0.0,
    presence_penalty=0.0,
    stop=None
  )
  try:
    response = completions.choices[0].text.strip()
    if len(response) < 500:
      return response
    else:
      lines = ['# Output generated by @ua_chatgpt_bot', f"Ваше питання: {prompt}" , f"Відповідь: {response}"]
      f = open(f'outs/{user_id}.txt', 'w', encoding='utf-8')
      for line in lines:
        f.write(line)
        f.write('\n\n')
    return response
  except Exception as _ex:
    pass

async def rich_generate_response(prompt):
    completions = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        temperature=1,
        max_tokens=1024,
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0,
        stop=None
    )
    message = completions.choices[0].text
    return message.strip()


async def translate_response(text):
    return translator.translate(text, dest='uk').text


async def translate_request(text):
    return translator.translate(text, dest='en').text
